# Generated by Django 3.2.13 on 2022-04-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniqueID', models.IntegerField()),
                ('Company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact_person_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Contact_phone', models.IntegerField()),
                ('Contact_email', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
